name: iso_base_media
description: A dart package to parse ISO Base Media File Format (e.g. MP4, HEIC, AVIF, JXL files).
version: 5.0.0
repository: https://github.com/mgenware/iso_base_media

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  random_access_source: ^3.1.0

dev_dependencies:
  mgenware_dart_lints: ^8.0.0
  test: ^1.24.0
