name: iso_base_media
description: A dart package to parse ISO Base Media File Format.
version: 6.3.0
repository: https://github.com/mgenware/iso_base_media

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  random_access_source: ^4.0.0
  web: ^1.1.1

dev_dependencies:
  mgenware_dart_lints: ^8.0.0
  test: ^1.24.0
